global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'devops'
    static_configs:
      - targets: ['host1ip:9100','host2ip:9100']

  - job_name: server_nginx
    scrape_interval: 5s
    static_configs:
      - targets: ['host3ipfornginx:9113']
        labels:
          alias: nginx_server

  - job_name: 'uptime'
    scrape_interval: 30s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['uptimekumahostip:3001']
    basic_auth: # Only needed if authentication is enabled (default)
      username: amit
      password: password
